title: Monika Gundecha
logo: /Picsart_24-02-21_15-00-49-987~2.jpg
description: From exploring stars to working in education for over 6 years, data has been a constant companion, leading me to pursue a Master's in Data Analytics at Northeastern University. I am passionate about utilizing raw data to craft compelling narratives that drive organizational growth and tackle real-world challenges.
#show_downloads: true
theme: jekyll-theme-minimal
