title: Monika Gundecha
logo: /Picsart_24-02-21_15-00-49-987~2.jpg
description: From exploring stars to working in education for over 6 years, I have embarked on a transformative journey where data has been a constant companion. This path has led me to pursue a Master's in Data Analytics at Northeastern University. I am passionate about harnessing the power of raw data to craft compelling narratives that uncover truths, foster organizational growth, and solve real-world challenges. Let's collaborate and leverage analytics to make informed decisions and drive meaningful impact together!
#show_downloads: true
theme: jekyll-theme-minimal
