title: Monika Gundecha
logo: /Picsart_24-02-21_15-00-49-987~2.jpg
description: An educator turned data analyst. I am passionate about utilizing raw data to craft narratives that drive organizational growth and tackle real-world challenges.
#show_downloads: true
theme: jekyll-theme-minimal
